### PR TITLE
Fix handling of multiple models in palaeorotate

### LINKED ISSUE #92: Multimodel binding issue in palaeorotate
When calling multiple GPMs at once, there seems to be a binding issue with the palaeocoordinates. Note, this is not an issue if palaeorotations are generated iteratively and must be related to chunk handling. This should be resolved quickly.

### PR DESCRIPTION
**Pull request by LewisAJones**
This PR gives a much needed update to `palaeorotate`. It fixes the issue with multimodel binding of the palaeocoordinates and significantly improves how API requests are handled. This has required a major rewrite of the code. However, it now allows for models to be easily added/removed when changes are made to the GPlates Web Service (expected soon).

Fixes #92.

### CODE REVIEW

File: R/palaeorotate.R [hunk 1]
```diff
@@ -419,108 +419,130 @@ palaeorotate <- function(occdf, lng = "lng", lat = "lat", age = "age",
...
+                times = 5,
+                pause_min = 1,
+                pause_base = 1,
+                pause_cap = 10)
+        })
+        # Extract coordinates
+        rots <- lapply(rots, function(x) {
+          coords <- content(x = x, as = "parsed")$coordinates
+          # Replace NULL values
+          rpl <- unlist(lapply(coords, is.null))
```
Comment (willgearty) [inline R/palaeorotate.R:511]: sapply?

File: R/palaeorotate.R [hunk 2]
```diff
@@ -419,108 +419,130 @@ palaeorotate <- function(occdf, lng = "lng", lat = "lat", age = "age",
       },
       error = function(e) {
         stop(paste("GPlates Web Service is not available.",
-      "Either the website is down or you are not connected to the internet."),
+                   "Either the website is down or you are not connected to the internet."),
```
Comment (willgearty) [inline R/palaeorotate.R:422]: line is too long

File: R/palaeorotate.R [hunk 3]
```diff
@@ -419,108 +419,130 @@ palaeorotate <- function(occdf, lng = "lng", lat = "lat", age = "age",
...
              call. = FALSE)
       })
+
+    # Set-up for point method -------
+    # Define root
+    pbase <- "https://gws.gplates.org/reconstruct/reconstruct_points/"
+    # Setup query structure
+    query <- list(points = NULL, time = NULL,
+                  model = NULL, anchor_plate_id = 0,
```
Comment (willgearty) [inline R/palaeorotate.R:431]: Does this anchor plate id matter? Should we document that we are using `0`?

File: R/palaeorotate.R [hunk 4]
```diff
@@ -419,108 +419,130 @@ palaeorotate <- function(occdf, lng = "lng", lat = "lat", age = "age",
...
+                url = pbase,
+                query = x,
+                times = 5,
+                pause_min = 1,
+                pause_base = 1,
+                pause_cap = 10)
+        })
+        # Extract coordinates
+        rots <- lapply(rots, function(x) {
+          coords <- content(x = x, as = "parsed")$coordinates
```
Comment (willgearty) [inline R/palaeorotate.R:509]: I'd be careful using the same variable name as a global variable (seems to work fine here, but it definitely makes reading the code confusing)

**Review by willgearty — CHANGES_REQUESTED** [review]
Just a few comments. Otherwise, code seems to look good and work as desired!

File: R/palaeorotate.R [hunk 5]
```diff
@@ -419,108 +419,130 @@ palaeorotate <- function(occdf, lng = "lng", lat = "lat", age = "age",
...
-              rots[[r]] <- list(NA, NA)
-            }
+        # Build requests
+        request <- lapply(tmp, function(x) {
+          req <- query[[m]]
+          req$time <- i
+          req$model <- m
+          pts <- paste(x[, lng], x[, lat], sep = ",")
+          pts <- toString(pts)
+          pts <- gsub(" ", "", pts)
```
Comment (willgearty) [inline R/palaeorotate.R:493]: I think this can be replaced with just the following:
`paste(x[, lng], x[, lat], sep = ",", collapse = ",")`

File: R/palaeorotate.R (hunk 3 above)
Comment (LewisAJones) [reply R/palaeorotate.R:431]: This basically indicates using their default reference frame (palaeomagnetic/mantle). For the models currently included it doesn't really matter. However, some of the new models being added are in a mantle reference frame (e.g. TorsvikCocks2017) by default and will need specifying as 1 to shift them to their palaeomagnetic reference frame. I don't think we need to update this now as it is the default behaviour. However, when we implement the major update coming, we will specify that all models are in their palaeomagnetic reference frame.

**Comment by LewisAJones** [comment]
Thanks for the quick review @willgearty! I've implemented all your suggestions so I think we're good to go?

**Review by willgearty — APPROVED** [review]
Looks good to me, thanks!
